### ISSUE TITLE
New Issue Template for Reporting a Bug

### ISSUE THREAD

**Issue by agung2001** [turtlepod/fx-editor#10]
Hi David, 👋😄  
my name is agung,  
I'm also from Indonesia.

I just found some interesting GitHub Issue templates for reporting a bug in [here](https://github.com/stevemao/github-issue-templates/blob/master/.github/ISSUE_TEMPLATE/BUG-REPORT.yml)
If that's ok for you I would like to contribute to this repo by creating a pull request containing the new template.
You can review the changes and decide to merge them later.

I know this is one of your old plugin projects, but I think it's still gonna be useful if we add those.  
so what do u think, just let me know  
thanks, David 😄👍

**Comment by turtlepod** [comment]
Hi @agung2001 ,
Sorry, I don't have time to do all that.
I think it's best for you to simply fork this plugin :)
